name: Glory of Nephilim Build and Test

on:
  push:
    paths:
      - .*
  create:
  pull_request:
    paths:
      - .*
    types: [opened, reopened, ready_for_review, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3

      - name: NPM Install
        run: npm ci

      - name: Build
        run: npx ng build
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3

      - name: NPM Install
        run: npm ci

      - name: Lint
        run: npx ng lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3

      - name: NPM Install
        run: npm ci

      - name: Test
        run: npx ng test
